### PR TITLE
Orion Plugin and Umple Server created

### PR DESCRIPTION
**Pull request by nwam**
This request includes an Orion plugin and an Umple Server.
The Orion plugin sends requests of a username a filenames to the Umple Server.
The Umple server generates files for the requested files under the requested user.

Note: you need to disable permissions/security for the plugin to work since it runs on localhost.

### CODE REVIEW

**Comment by vahdat-ab** [comment]
I wonder if you can make these available in Docker?
Otherwise, please tell me the structure of the project and the steps need to be followed.
I think the Docker is the best one it will save you time regarding describing how it work and etc.

**Comment by vahdat-ab** [comment]
@nwam I tried to compile the project but I'm getting issues regarding mismatch of java version and dependencies. I wonder if there is a special process needs to be done? Or if you missed putting the correct `pom` file?

**Comment by vahdat-ab** [comment]
had to add these lines to `pom`.

```XML
    <!-- make sure you have umple.jar in your local repository -->
    <dependency>
			<groupId>cruise.umple</groupId>
			<artifactId>umple</artifactId>
			<version>1.25.0-963d2bd</version>
    </dependency>
```
```XML
  <!-- This is to make sure the system is going to use java 8 -->
  <properties>
  <maven.compiler.source>1.8</maven.compiler.source>
  <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
```
It builds but still cannot run and see the results

**Comment by nwam** [comment]
My most recent commit makes Docker usable again (on my machine at least). Let me know if there are any issues.

**Comment by vahdat-ab** [comment]
@nwam I tried to build the docker but I couldn't. I tried both in Windows and Linux Ubuntu.
It is  terminated with the following error:
```
Removing intermediate container aae596aee8b9
Step 7 : ADD umple-orion-server/target/umple-orion-server-*-jar-with-dependencies.jar /opt/umple-orion-server/umple-orion-server.jar
No source files were specified
Unable to find image 'umple_orion:latest' locally
Pulling repository docker.io/library/umple_orion
docker: Error: image library/umple_orion:latest not found.
See 'docker run --help'.
```

Is there a specific thing needs to be done?
I just run `set_up_and_run_docker`

**Comment by nwam** [comment]
@vahdat-ab  Try rerunning it now after pulling my changes. If you get a similar error, let me know if the file `umple-orion-server/target/umple-orion-server-0.2-jar-with-dependencies.jar` or `umple-orion-server/target/umple-orion-server-jar-with-dependencies.jar` is in place. 

There was an error while running the `Dockerfile` because it couldn't find `umple-orion-server-*-jar-with-dependencies.jar`. Either Docker has issues handling wildcards, or the jar was not built correctly.

**Comment by vahdat-ab** [comment]
not working yet in my side

**Comment by nwam** [comment]
@vahdat-ab  I just ran the setup script from a fresh Docker slate and a fresh pull of my fork and it works without issues. Perhaps you are not running the script from the root directory of the repository?

**Comment by vahdat-ab** [comment]
great. I could run it.
The HTTPs issue is still there and also when you run this example
```
namespace std;
class A{
	
}
```
It generates the code under a folder called `test-Java-Gen-Umple` or `test-RTCpp-Gen-Umple` based on the language.
I merge this and then you can fix them under another issue

**Pull request merged**
